### PR TITLE
bugfix: not a valid metric name  source=emq_exporter.go:99

### PR DESCRIPTION
**Pull request by cai-personal**
https://github.com/nuvo/emq_exporter/issues/17

【emq  version: 3.2】

### CODE REVIEW

**Comment by boddumanohar** [comment]
@fangjianfeng you might have to replace multiple such `.`. Its better if you use `strings.NewReplacer`

**Comment by cai-personal** [comment]
> @fangjianfeng you might have to replace multiple such `.`. Its better if you use `strings.NewReplacer`

got it

**Comment by juris** [comment]
ping

**Comment by Zeka13** [comment]
@HagaiBarel wazup

**Comment by mossad-zika** [comment]
@HagaiBarel shalom!

**Comment by hagaibarel** [comment]
Hi, I'm no longer maintaining this project, pinging @tomklino

**Comment by AhmarRG** [comment]
Hi!
   I'm getting the same issue.
Is there any update?

**Comment by hagaibarel** [comment]
Merged into v0.4.2, give it a go an let me know

**Comment by AhmarRG** [comment]
Working fine now, thanks

**Comment by AhmarRG** [comment]
Does it support cluster(multiple nodes) metrics?

**Pull request merged**
